
#--------------------------------APPLICATION PROPERTY FILE: ISSUANCE CARD-------------------
#APPLICATION CONFIGS

spring.application.name=mobileshop

# Railway PORT deil; local sathi 8080
server.port=${PORT:8080}
server.servlet.context.path=/jagadamb/electronics

# Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.username=${MAIL_USERNAME:shivaratnaraut@gmail.com}
spring.mail.password=${MAIL_PASSWORD:ogxizhwlidoezfny}

# Database profile
spring.profiles.active=no-kafka,${ACTIVE_DB_PROFILE:local}


# JWT
jwt.secret=${JWT_SECRET:JagadambaMobileShopSecretKeyForJwtToken123456789}
jwt.expiration=${JWT_EXPIRATION:86400000}